// On-device benchmark firmware for the WiFi-CSI architecture comparison.
// Loads one int8 TFLite model, runs 1000 inferences on a fixed input, and prints
// latency and peak RAM. Swap the included model array per architecture and re-flash.
//
// To use a model: xxd -i CNN_int8.tflite > model_cnn.cc, then make sure the extern
// names below match the array name in that file (xxd derives it from the filename).
#include <cstdio>
#include <cstring>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_timer.h"
#include "esp_heap_caps.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ---- model array (generated by esp32_firmware/tflite_to_c.py into model_tiny.cc). ----
extern const unsigned char model_data_tflite[];
extern const unsigned int  model_data_tflite_len;
#define MODEL_DATA model_data_tflite

// UT-HAR input is 250 packets x 90 features = 22500 int8 values.
static constexpr int kInputSize = 250 * 90;
// Classic ESP32 has no PSRAM and ~300 kB usable internal SRAM. Start at 256 kB;
// if AllocateTensors fails the model does not fit on this chip (an honest result).
static constexpr int kArenaSize = 256 * 1024;

extern "C" void app_main(void) {
    // No PSRAM on the classic ESP32: take the largest available contiguous internal
    // block (capped at kArenaSize), leaving a small margin for the interpreter itself.
    size_t big = heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL);
    size_t want = (size_t)kArenaSize;
    size_t asize = (want < big) ? want : (big > (2*1024) ? big - (2*1024) : big);
    uint8_t* tensor_arena = (uint8_t*) heap_caps_malloc(asize, MALLOC_CAP_INTERNAL);
    printf("arena_alloc_bytes = %u  (largest_free_internal = %u)\n",
           (unsigned)asize, (unsigned)big);
    if (tensor_arena == nullptr) { printf("ARENA ALLOC FAILED\n"); return; }

    const tflite::Model* model = tflite::GetModel(MODEL_DATA);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        printf("SCHEMA MISMATCH\n");
        return;
    }
    // Broad op set covering the tiny CNN/MLP (Conv1D decomposes to ExpandDims+Conv2D,
    // GlobalAveragePooling1D to Mean) plus the deep models.
    static tflite::MicroMutableOpResolver<22> resolver;
    resolver.AddConv2D();        resolver.AddDepthwiseConv2D();
    resolver.AddFullyConnected();resolver.AddReshape();
    resolver.AddMaxPool2D();     resolver.AddMean();          // global avg pool
    resolver.AddSoftmax();       resolver.AddRelu();
    resolver.AddAdd();           resolver.AddMul();
    resolver.AddSub();           resolver.AddTanh();
    resolver.AddConcatenation(); resolver.AddQuantize();
    resolver.AddDequantize();    resolver.AddLogistic();
    resolver.AddStridedSlice();  resolver.AddPack();
    resolver.AddExpandDims();    resolver.AddShape();
    resolver.AddAveragePool2D(); resolver.AddTranspose();

    static tflite::MicroInterpreter interp(model, resolver, tensor_arena, asize);
    if (interp.AllocateTensors() != kTfLiteOk) {
        printf("ALLOC FAIL (increase kArenaSize)\n");
        return;
    }
    printf("arena_used_bytes = %d   (-> Peak RAM kB = %.1f)\n",
           (int)interp.arena_used_bytes(), interp.arena_used_bytes() / 1024.0);

    TfLiteTensor* in = interp.input(0);
    // fixed dummy input (latency/RAM do not depend on input content).
    // Use the tensor's actual byte size so this works for any input window.
    for (size_t i = 0; i < in->bytes; i++) in->data.int8[i] = 0;

    interp.Invoke();  // warm-up

    // Time 1000 invocations in batches, yielding between batches so the idle task
    // feeds the task watchdog. Only the Invoke calls are timed, so the yield does
    // not affect the reported latency.
    const int BATCHES = 20, PER = 50, N = BATCHES * PER;
    int64_t acc = 0;
    for (int b = 0; b < BATCHES; b++) {
        int64_t t0 = esp_timer_get_time();
        for (int i = 0; i < PER; i++) interp.Invoke();
        acc += esp_timer_get_time() - t0;
        vTaskDelay(1);  // not counted in acc
    }
    printf("latency_ms = %.3f\n", (double)acc / 1000.0 / N);
    printf("free_internal = %d, free_psram = %d\n",
           (int)heap_caps_get_free_size(MALLOC_CAP_INTERNAL),
           (int)heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
    printf("DONE\n");
}
