// On-device benchmark firmware for the WiFi-CSI architecture comparison.
// Loads one int8 TFLite model, runs 1000 inferences on a fixed input, and prints
// latency and peak RAM. Swap the included model array per architecture and re-flash.
//
// To use a model: xxd -i CNN_int8.tflite > model_cnn.cc, then make sure the extern
// names below match the array name in that file (xxd derives it from the filename).
#include <cstdio>
#include <cstring>
#include <cmath>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_timer.h"
#include "esp_heap_caps.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ---- model array (generated by esp32_firmware/tflite_to_c.py into model_tiny.cc). ----
extern const unsigned char model_data_tflite[];
extern const unsigned int  model_data_tflite_len;
#define MODEL_DATA model_data_tflite

#ifdef REPLAY_DEMO
// Item #11: stored real CSI windows (int8) generated by csi_replay.ipynb.
#include "replay_windows.h"
#endif

// UT-HAR input is 250 packets x 90 features = 22500 int8 values.
static constexpr int kInputSize = 250 * 90;
// Classic ESP32 has no PSRAM and ~300 kB usable internal SRAM. Start at 256 kB;
// if AllocateTensors fails the model does not fit on this chip (an honest result).
static constexpr int kArenaSize = 256 * 1024;

extern "C" void app_main(void) {
    // No PSRAM on the classic ESP32: take the largest available contiguous internal
    // block (capped at kArenaSize), leaving a small margin for the interpreter itself.
    size_t big = heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL);
    size_t want = (size_t)kArenaSize;
    size_t asize = (want < big) ? want : (big > (2*1024) ? big - (2*1024) : big);
    uint8_t* tensor_arena = (uint8_t*) heap_caps_malloc(asize, MALLOC_CAP_INTERNAL);
    printf("arena_alloc_bytes = %u  (largest_free_internal = %u)\n",
           (unsigned)asize, (unsigned)big);
    if (tensor_arena == nullptr) { printf("ARENA ALLOC FAILED\n"); return; }

    const tflite::Model* model = tflite::GetModel(MODEL_DATA);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        printf("SCHEMA MISMATCH\n");
        return;
    }
    // Broad op set covering the tiny CNN/MLP (Conv1D decomposes to ExpandDims+Conv2D,
    // GlobalAveragePooling1D to Mean) plus the deep models.
    static tflite::MicroMutableOpResolver<40> resolver;
    resolver.AddConv2D();        resolver.AddDepthwiseConv2D();
    resolver.AddFullyConnected();resolver.AddReshape();
    resolver.AddMaxPool2D();     resolver.AddMean();          // global avg pool
    resolver.AddSoftmax();       resolver.AddRelu();
    resolver.AddAdd();           resolver.AddMul();
    resolver.AddSub();           resolver.AddTanh();
    resolver.AddConcatenation(); resolver.AddQuantize();
    resolver.AddDequantize();    resolver.AddLogistic();
    resolver.AddStridedSlice();  resolver.AddPack();
    resolver.AddExpandDims();    resolver.AddShape();
    resolver.AddAveragePool2D(); resolver.AddTranspose();
    resolver.AddBatchMatMul();   resolver.AddGather();        // Transformer attention
    resolver.AddCast();          resolver.AddSlice();
    resolver.AddNeg();           resolver.AddFill();          // Transformer / KAN
    resolver.AddSquaredDifference(); resolver.AddRsqrt();     // LayerNorm
    resolver.AddSquare();        resolver.AddExp();
    resolver.AddSplit();         resolver.AddPad();

    static tflite::MicroInterpreter interp(model, resolver, tensor_arena, asize);
    if (interp.AllocateTensors() != kTfLiteOk) {
        printf("ALLOC FAIL (increase kArenaSize)\n");
        return;
    }
    printf("arena_used_bytes = %d   (-> Peak RAM kB = %.1f)\n",
           (int)interp.arena_used_bytes(), interp.arena_used_bytes() / 1024.0);

    TfLiteTensor* in = interp.input(0);

#ifdef REPLAY_DEMO
    // Item #11: replay stored real CSI windows through the on-device interpreter
    // and print the prediction per window. Demonstrates end-to-end classification
    // of real CSI on the bare ESP32, not just latency on a dummy input.
    TfLiteTensor* out = interp.output(0);
    int correct = 0;
    for (int w = 0; w < REPLAY_N; w++) {
        for (int j = 0; j < REPLAY_T * REPLAY_F; j++)
            in->data.int8[j] = kReplayWindows[w][j];
        if (interp.Invoke() != kTfLiteOk) { printf("replay invoke failed\n"); continue; }
        int ncls = (int)out->bytes;
        int best = 0; int8_t bv = out->data.int8[0];
        for (int c = 1; c < ncls; c++) if (out->data.int8[c] > bv) { bv = out->data.int8[c]; best = c; }
        int truth = kReplayTrueLabel[w];
        bool ok = (best == truth);
        if (ok) correct++;
        printf("replay window %d: true=%s pred=%s %s\n", w,
               kReplayClassNames[truth], kReplayClassNames[best], ok ? "OK" : "MISS");
        vTaskDelay(1);
    }
    printf("replay_accuracy = %d/%d\n", correct, REPLAY_N);
    printf("DONE\n");
    return;
#endif

    // fixed dummy input (latency/RAM do not depend on input content).
    // Use the tensor's actual byte size so this works for any input window.
    for (size_t i = 0; i < in->bytes; i++) in->data.int8[i] = 0;

    interp.Invoke();  // warm-up

    // Time 1000 invocations individually to report both mean and standard
    // deviation of per-inference latency. Only the Invoke call is timed; a short
    // yield after every run feeds the task watchdog and is not counted. Yielding
    // every run (rather than every N) is robust to slower deep models whose single
    // inference can approach the 5 s watchdog window when yields are spaced out.
    const int N = 1000;
    double sum = 0.0, sumsq = 0.0;
    for (int n = 0; n < N; n++) {
        int64_t t0 = esp_timer_get_time();
        interp.Invoke();
        double ms = (double)(esp_timer_get_time() - t0) / 1000.0;
        sum += ms;
        sumsq += ms * ms;
        vTaskDelay(1);  // feed watchdog between timed runs (not counted)
    }
    double mean = sum / N;
    double var = sumsq / N - mean * mean;
    double sd = (var > 0) ? sqrt(var) : 0.0;
    printf("latency_ms = %.3f\n", mean);
    printf("latency_std_ms = %.4f\n", sd);
    printf("throughput_win_per_s = %.2f\n", 1000.0 / mean);
    printf("free_internal = %d, free_psram = %d\n",
           (int)heap_caps_get_free_size(MALLOC_CAP_INTERNAL),
           (int)heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
    printf("DONE\n");
}
